// <auto-generated />
namespace ProyectPrueba.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class prueba0005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prueba0005));
        
        string IMigrationMetadata.Id
        {
            get { return "201809160642141_prueba0005"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
